# Generated by Django 4.2 on 2023-05-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
